@echo off
echo Copying Vercel package.json...
copy package.json.vercel package.json
echo Installing Next.js and React...
npm install next@13.4.19 react@18.2.0 react-dom@18.2.0
echo Building Next.js application...
npx next build
