/**
 * Sports Gambling Data Models
 *
 * These models define the structure for sports gambling functionality
 * including games, teams, betting lines, and picks.
 */

// Sport Types
export type SportType = 'NFL' | 'NBA' | 'MLB' | 'NHL' | 'NCAAF' | 'NCAAB';

/**
 * Team Model
 * 
 * Represents a sports team with basic information
 */
export interface Team {
  id: string;
  name: string;
  abbreviation: string;
  location: string;
  mascot?: string;
  conference?: string;
  division?: string;
  logo?: string;
}

/**
 * Game Model
 * 
 * Represents a sports game with teams and betting information
 */
export interface Game {
  id: string;
  sport: SportType;
  homeTeam: Team;
  awayTeam: Team;
  startTime: Date;
  location: string;
  stadium?: string;
  weather?: string;
  status: 'scheduled' | 'in_progress' | 'final' | 'postponed' | 'canceled';
  homeScore?: number;
  awayScore?: number;
  bettingLines: BettingLine[];
}

/**
 * Betting Line Model
 * 
 * Represents betting odds and lines for a game
 */
export interface BettingLine {
  id: string;
  gameId: string;
  sportsbook: string;
  timestamp: Date;
  spread: {
    homeSpread: number;
    homeOdds: number;
    awaySpread: number;
    awayOdds: number;
  };
  moneyline: {
    homeOdds: number;
    awayOdds: number;
    drawOdds?: number;
  };
  total: {
    over: number;
    overOdds: number;
    under: number;
    underOdds: number;
  };
}

/**
 * Betting Pick Model
 * 
 * Represents a betting pick with prediction and confidence
 */
export interface BettingPick {
  id: string;
  gameId: string;
  game: Game;
  pickType: 'spread' | 'moneyline' | 'total' | 'prop';
  team?: 'home' | 'away';
  pick: string;
  odds: number;
  confidence: number; // 1-10 scale
  analysis: string;
  result?: 'win' | 'loss' | 'push' | 'pending';
  createdAt: Date;
  postedAt?: Date;
  tweetId?: string;
}

/**
 * Daily Picks Model
 * 
 * Represents a collection of daily betting picks
 */
export interface DailyPicks {
  id: string;
  date: Date;
  picks: BettingPick[];
  status: 'pending' | 'posted' | 'completed';
  tweetId?: string;
  performance?: {
    wins: number;
    losses: number;
    pushes: number;
    roi: number;
  };
}

// Mock data functions
export function getMockGames(): Game[] {
  // This would be replaced with actual data from a sports API
  return [];
}

export function getMockBettingPicks(): BettingPick[] {
  // This would be replaced with actual picks generated by the algorithm
  return [];
}
